/**
 * @file dashboardData.ts
 * @description Dados históricos fictícios realistas e helpers estatísticos para o Dashboard Gerencial.
 * Inclui dados completos de perfil do suspeito para alimentar os indicadores de BI (Gênero, Cor da Pele, Faixa Etária, Estatura, Vestimenta e Cruzamento com Setor/Loja).
 */

import { UnifiedEventRecord, EventCategoryKey, SuspectProfile } from '../types';

export const INITIAL_HISTORICAL_EVENTS: UnifiedEventRecord[] = [
  {
    id: 'evt-live-01',
    protocol: 'MOB-2026-90412',
    source: 'RONDA_MOBILE',
    branch: '01 - CEILÂNDIA 070',
    category: 'furto',
    categoryLabel: 'Furto',
    timestamp: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
    lossValue: 860.00,
    recoveredValue: 0.00,
    status: 'PENDENTE',
    operatorOrAgent: 'Fiscal Ronda #088 (Tiago Silva)',
    cameraOrLocation: 'Corredor 04 - Bebidas Quentes',
    summary: 'Suspeito masculino com jaqueta escura e mochila forrada colocando 3 garrafas de whisky importado. Solicitado apoio de câmera PTZ.',
    evidenceCount: 1,
    evidenceUrl: 'https://images.unsplash.com/photo-1557597774-9d273605dfa9?auto=format&fit=crop&w=600&q=80',
    productSector: 'Bebidas Quentes / Destilados',
    fieldReport: {
      locationAddress: 'Atacadão Dia a Dia - Ceilândia 070 (Corredor 04)',
      agentNotes: 'Indivíduo demonstrou nervosismo ao avistar o fiscal e se deslocou em direção aos caixas rápidos.',
      agentName: 'Fiscal Ronda #088 (Tiago Silva)',
      photoUrl: 'https://images.unsplash.com/photo-1557597774-9d273605dfa9?auto=format&fit=crop&w=600&q=80',
      timestamp: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
      initialCategory: 'furto',
    },
    suspectProfile: {
      gender: 'masculino',
      skinTone: 'parda',
      ageRange: '26_35',
      heightRange: 'medio',
      clothingStyle: 'jaqueta_casaco_pesado',
      clothingDetails: 'Jaqueta corta-vento preta, calça jeans escura',
      carryingAccessories: ['Mochila Térmica / Forrada', 'Boné / Chapéu / Gorro'],
    },
    details: {
      categoryData: {
        sector: 'Bebidas Quentes / Destilados',
        itemCategory: 'Destilados Importados',
        estimatedLossValue: '860,00',
        recoveryStatus: 'nao_recuperado',
        suspectsCount: '1',
      }
    }
  },
  {
    id: 'evt-live-02',
    protocol: 'MOB-2026-90388',
    source: 'RONDA_MOBILE',
    branch: '08 - TAGUATINGA',
    category: 'inibicao',
    categoryLabel: 'Inibição',
    timestamp: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
    lossValue: 0.00,
    recoveredValue: 1250.00,
    status: 'EM_ANALISE',
    operatorOrAgent: 'Fiscal Ronda #102 (Camila R.)',
    assignedOperator: 'Operador CFTV #402 (Lucas M.)',
    claimedAt: new Date(Date.now() - 4 * 60 * 1000 - 32 * 1000).toISOString(),
    cameraOrLocation: 'Corredor 09 - Perfumaria & Higiene',
    cameraAssigned: 'CAM-08',
    cameraSector: 'Corredor Perfumaria / Cosméticos',
    summary: 'Dupla feminina selecionando múltiplos kits de desodorantes e perfumes caros. Operador CFTV acompanhando via CAM-08.',
    evidenceCount: 1,
    evidenceUrl: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=600&q=80',
    productSector: 'Perfumaria / Higiene & Beleza',
    fieldReport: {
      locationAddress: 'Atacadão Dia a Dia - Taguatinga (Setor Cosméticos)',
      agentNotes: 'Suspeitas colocaram itens em bolsas grandes. Posicionei ronda próxima ao setor.',
      agentName: 'Fiscal Ronda #102 (Camila R.)',
      photoUrl: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=600&q=80',
      timestamp: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
      initialCategory: 'inibicao',
    },
    suspectProfile: {
      gender: 'dupla_mista',
      skinTone: 'branca',
      ageRange: '18_25',
      heightRange: 'medio',
      clothingStyle: 'vestido_saia',
      clothingDetails: 'Vestido longo e blusa clara, bolsas laterais',
      carryingAccessories: ['Bolsa Feminina Grande', 'Óculos Escuros / Grau'],
    },
    details: {
      categoryData: {
        sectorProtected: 'Perfumaria / Higiene & Beleza',
        estimatedProtectedValue: '1.250,00',
        preventionMethod: 'Monitoramento contínuo por CFTV com direcionamento de fiscal',
      }
    }
  },
  {
    id: 'evt-live-03',
    protocol: 'MOB-2026-90299',
    source: 'RONDA_MOBILE',
    branch: '07 - SIA',
    category: 'furto',
    categoryLabel: 'Furto',
    timestamp: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    lossValue: 680.00,
    recoveredValue: 0.00,
    status: 'PENDENTE',
    operatorOrAgent: 'Fiscal Ronda #044 (Bruno Ramos)',
    cameraOrLocation: 'Ilha Central - Carnes Nobres',
    summary: 'Cliente guardou 4 peças de picanha dentro do casaco e caminha rumo ao setor de hortifrúti.',
    evidenceCount: 1,
    evidenceUrl: 'https://images.unsplash.com/photo-1541888946425-d0fbb18086f6?auto=format&fit=crop&w=600&q=80',
    productSector: 'Carnes Nobres / Açougue',
    fieldReport: {
      locationAddress: 'Atacadão Dia a Dia - SIA (Ilha de Frios & Carnes Nobres)',
      agentNotes: 'Suspeito de meia idade com casaco volumoso. Aguardando validação de filmagem para abordagem externa.',
      agentName: 'Fiscal Ronda #044 (Bruno Ramos)',
      photoUrl: 'https://images.unsplash.com/photo-1541888946425-d0fbb18086f6?auto=format&fit=crop&w=600&q=80',
      timestamp: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
      initialCategory: 'furto',
    },
    suspectProfile: {
      gender: 'masculino',
      skinTone: 'branca',
      ageRange: '36_50',
      heightRange: 'alto',
      clothingStyle: 'jaqueta_casaco_pesado',
      clothingDetails: 'Casaco preto grosso com bolsos largos',
      carryingAccessories: ['Cinto / Suporte Oculto'],
    },
    details: {
      categoryData: {
        sector: 'Carnes Nobres / Açougue',
        itemCategory: 'Carnes Nobres & Frios',
        estimatedLossValue: '680,00',
        recoveryStatus: 'nao_recuperado',
      }
    }
  },
  {
    id: 'evt-hist-01',
    protocol: 'EVT-2026-84920',
    source: 'CENTRAL_CFTV',
    branch: '07 - SIA',
    category: 'furto',
    categoryLabel: 'Furto',
    timestamp: '2026-08-15T10:14:22',
    lossValue: 1450.00,
    recoveredValue: 1450.00,
    status: 'CONCLUIDO',
    operatorOrAgent: 'Operador CFTV #402 (Lucas M.)',
    cameraOrLocation: 'CAM-14 (Setor Bebidas Quentes)',
    summary: 'Indivíduo tentou ocultar 4 garrafas de whisky importado em mochila térmica. Abordado na saída com apoio da ronda.',
    evidenceCount: 3,
    productSector: 'Bebidas Quentes / Destilados',
    suspectProfile: {
      gender: 'masculino',
      skinTone: 'parda',
      ageRange: '26_35',
      heightRange: 'medio',
      clothingStyle: 'jaqueta_casaco_pesado',
      clothingDetails: 'Jaqueta escura fechada, calça jeans',
      carryingAccessories: ['Mochila Térmica / Forrada', 'Boné / Chapéu / Gorro'],
    },
    details: {
      categoryData: {
        sector: 'Bebidas Quentes / Destilados',
        itemCategory: 'Destilados',
        estimatedLossValue: '1.450,00',
        recoveryStatus: 'recuperado_total',
      }
    }
  },
  {
    id: 'evt-hist-02',
    protocol: 'EVT-2026-84812',
    source: 'RONDA_MOBILE',
    branch: '01 - CEILÂNDIA 070',
    category: 'inibicao',
    categoryLabel: 'Inibição',
    timestamp: '2026-08-15T09:30:15',
    lossValue: 0.00,
    recoveredValue: 890.00,
    status: 'CONCLUIDO',
    operatorOrAgent: 'Fiscal Ronda #118 (Marcos S.)',
    cameraOrLocation: 'Corredor 09 - Perfumaria / Bazar',
    summary: 'Presença ostensiva inibiu tentativa de rompimento de lacres em kit de ferramentas e desodorantes.',
    evidenceCount: 1,
    productSector: 'Perfumaria / Higiene & Beleza',
    suspectProfile: {
      gender: 'masculino',
      skinTone: 'parda',
      ageRange: '18_25',
      heightRange: 'baixo',
      clothingStyle: 'moletom_capuz',
      clothingDetails: 'Moletom com capuz cinza, bermuda',
      carryingAccessories: ['Boné / Chapéu / Gorro', 'Mochila Convencional'],
    },
  },
  {
    id: 'evt-hist-03',
    protocol: 'EVT-2026-83901',
    source: 'CENTRAL_CFTV',
    branch: '08 - TAGUATINGA',
    category: 'furto',
    categoryLabel: 'Furto',
    timestamp: '2026-08-14T17:45:00',
    lossValue: 850.00,
    recoveredValue: 850.00,
    status: 'CONCLUIDO',
    operatorOrAgent: 'Operador CFTV #305 (Carla V.)',
    cameraOrLocation: 'CAM-18 (Carnes Nobres & Frios)',
    summary: 'Suspeito inseriu 6 peças de picanha a vácuo sob a jaqueta. Detido na área externa.',
    evidenceCount: 2,
    productSector: 'Carnes Nobres / Açougue',
    suspectProfile: {
      gender: 'masculino',
      skinTone: 'branca',
      ageRange: '36_50',
      heightRange: 'alto',
      clothingStyle: 'jaqueta_casaco_pesado',
      clothingDetails: 'Casaco puffer preto volumoso',
      carryingAccessories: ['Cinto / Suporte Oculto'],
    },
  },
  {
    id: 'evt-hist-04',
    protocol: 'EVT-2026-83445',
    source: 'RONDA_MOBILE',
    branch: '13 - LUZIÂNIA',
    category: 'furto',
    categoryLabel: 'Furto',
    timestamp: '2026-08-14T14:20:10',
    lossValue: 620.00,
    recoveredValue: 310.00,
    status: 'CONCLUIDO',
    operatorOrAgent: 'Fiscal Ronda #092 (Rafael T.)',
    cameraOrLocation: 'Corredor 08 - Perfumaria',
    summary: 'Dupla feminina rompeu lacres de cremes importados e desodorantes em aerossol.',
    evidenceCount: 1,
    productSector: 'Perfumaria / Higiene & Beleza',
    suspectProfile: {
      gender: 'dupla_mista',
      skinTone: 'branca',
      ageRange: '18_25',
      heightRange: 'medio',
      clothingStyle: 'vestido_saia',
      clothingDetails: 'Vestido longo florido e bolsa lateral',
      carryingAccessories: ['Bolsa Feminina Grande', 'Óculos Escuros / Grau'],
    },
  },
  {
    id: 'evt-hist-05',
    protocol: 'EVT-2026-82910',
    source: 'CENTRAL_CFTV',
    branch: '17 - CD POLO JK',
    category: 'inibicao',
    categoryLabel: 'Inibição',
    timestamp: '2026-08-13T22:15:30',
    lossValue: 0.00,
    recoveredValue: 1200.00,
    status: 'CONCLUIDO',
    operatorOrAgent: 'Operador CFTV #109 (Juliano P.)',
    cameraOrLocation: 'CAM-09 (Bazar & Eletrônicos)',
    summary: 'Suspeito monitorado ao selecionar smartphones e pilhas de alto valor. Desistiu com aproximação do fiscal.',
    evidenceCount: 2,
    productSector: 'Eletrônicos / Telefonia & Bazar',
    suspectProfile: {
      gender: 'masculino',
      skinTone: 'preta',
      ageRange: '26_35',
      heightRange: 'alto',
      clothingStyle: 'camiseta_bermuda',
      clothingDetails: 'Camiseta estampada, bermuda jeans, óculos',
      carryingAccessories: ['Mochila Térmica / Forrada', 'Óculos Escuros / Grau'],
    },
  },
  {
    id: 'evt-hist-06',
    protocol: 'EVT-2026-82104',
    source: 'RONDA_MOBILE',
    branch: '04 - SOBRADINHO',
    category: 'furto',
    categoryLabel: 'Furto',
    timestamp: '2026-08-13T11:05:44',
    lossValue: 340.00,
    recoveredValue: 340.00,
    status: 'CONCLUIDO',
    operatorOrAgent: 'Fiscal Ronda #044 (Bruno R.)',
    cameraOrLocation: 'Corredor 12 - Mercearia Fina & Chocolates',
    summary: 'Ocultação de barras de chocolates nobres e doces finos em sacola reutilizável.',
    evidenceCount: 1,
    productSector: 'Mercearia de Alto Valor / Bomboniere',
    suspectProfile: {
      gender: 'feminino',
      skinTone: 'parda',
      ageRange: '36_50',
      heightRange: 'baixo',
      clothingStyle: 'camisa_social_polo',
      clothingDetails: 'Blusa social listrada, calça jeans clara',
      carryingAccessories: ['Sacola de Outro Estabelecimento', 'Bolsa Feminina Grande'],
    },
  },
  {
    id: 'evt-hist-07',
    protocol: 'EVT-2026-81502',
    source: 'CENTRAL_CFTV',
    branch: '28 - ÁGUAS CLARAS',
    category: 'furto',
    categoryLabel: 'Furto',
    timestamp: '2026-08-12T19:40:12',
    lossValue: 2100.00,
    recoveredValue: 2100.00,
    status: 'CONCLUIDO',
    operatorOrAgent: 'Operador CFTV #402 (Lucas M.)',
    cameraOrLocation: 'CAM-04 (Bebidas Quentes)',
    summary: 'Quadrilha de 3 elementos atuando em conjunto com mochila forrada com papel alumínio (bloqueador de sinal). Flagrante efetuado.',
    evidenceCount: 4,
    productSector: 'Bebidas Quentes / Destilados',
    suspectProfile: {
      gender: 'grupo_multiplo',
      skinTone: 'parda',
      ageRange: '26_35',
      heightRange: 'medio',
      clothingStyle: 'jaqueta_casaco_pesado',
      clothingDetails: 'Roupas escuras, jaquetas pesadas e bonés',
      carryingAccessories: ['Mochila Térmica / Forrada', 'Boné / Chapéu / Gorro'],
    },
  },
  {
    id: 'evt-hist-08',
    protocol: 'EVT-2026-80990',
    source: 'RONDA_MOBILE',
    branch: '32 - CEILÂNDIA CENTRO',
    category: 'inibicao',
    categoryLabel: 'Inibição',
    timestamp: '2026-08-12T16:10:00',
    lossValue: 0.00,
    recoveredValue: 750.00,
    status: 'CONCLUIDO',
    operatorOrAgent: 'Fiscal Ronda #081 (Diego M.)',
    cameraOrLocation: 'Corredor 05 - Açougue & Frios',
    summary: 'Aproximação de ronda inibiu ocultação de fardos de queijo e peças de carne sob casaco.',
    evidenceCount: 1,
    productSector: 'Carnes Nobres / Açougue',
    suspectProfile: {
      gender: 'masculino',
      skinTone: 'preta',
      ageRange: '26_35',
      heightRange: 'alto',
      clothingStyle: 'jaqueta_casaco_pesado',
      clothingDetails: 'Casaco de moletom azul escuro fechado',
      carryingAccessories: ['Boné / Chapéu / Gorro'],
    },
  },
  {
    id: 'evt-hist-09',
    protocol: 'EVT-2026-80411',
    source: 'CENTRAL_CFTV',
    branch: '07 - SIA',
    category: 'furto',
    categoryLabel: 'Furto',
    timestamp: '2026-08-11T13:30:20',
    lossValue: 980.00,
    recoveredValue: 980.00,
    status: 'CONCLUIDO',
    operatorOrAgent: 'Operador CFTV #201 (Renata C.)',
    cameraOrLocation: 'CAM-08 (Perfumaria & Lâminas)',
    summary: 'Ocultação de 12 cartelas de lâminas de barbear em bolso interno de jaqueta.',
    evidenceCount: 2,
    productSector: 'Perfumaria / Higiene & Beleza',
    suspectProfile: {
      gender: 'masculino',
      skinTone: 'parda',
      ageRange: '18_25',
      heightRange: 'baixo',
      clothingStyle: 'jaqueta_casaco_pesado',
      clothingDetails: 'Jaqueta corta-vento preta com bolsos fundos',
      carryingAccessories: ['Mochila Convencional'],
    },
  },
  {
    id: 'evt-hist-10',
    protocol: 'EVT-2026-79880',
    source: 'RONDA_MOBILE',
    branch: '29 - GUARÁ',
    category: 'colisao',
    categoryLabel: 'Colisão',
    timestamp: '2026-08-11T09:15:00',
    lossValue: 500.00,
    recoveredValue: 500.00,
    status: 'CONCLUIDO',
    operatorOrAgent: 'Fiscal Ronda #012 (Tiago V.)',
    cameraOrLocation: 'Estacionamento Vaga 44',
    summary: 'Abalroamento leve ao estacionar.',
    evidenceCount: 1,
  },
  {
    id: 'evt-hist-11',
    protocol: 'EVT-2026-79120',
    source: 'CENTRAL_CFTV',
    branch: '01 - CEILÂNDIA 070',
    category: 'furto',
    categoryLabel: 'Furto',
    timestamp: '2026-08-10T18:50:33',
    lossValue: 1600.00,
    recoveredValue: 1600.00,
    status: 'CONCLUIDO',
    operatorOrAgent: 'Operador CFTV #402 (Lucas M.)',
    cameraOrLocation: 'CAM-04 (Bebidas Quentes)',
    summary: 'Tentativa de evasão com 5 garrafas de gin e vodka sob casaco forrado.',
    evidenceCount: 3,
    productSector: 'Bebidas Quentes / Destilados',
    suspectProfile: {
      gender: 'masculino',
      skinTone: 'parda',
      ageRange: '26_35',
      heightRange: 'medio',
      clothingStyle: 'jaqueta_casaco_pesado',
      clothingDetails: 'Casaco de nylon cinza e calça preta',
      carryingAccessories: ['Mochila Térmica / Forrada'],
    },
  },
];

export const CATEGORY_COLORS: Record<EventCategoryKey, string> = {
  furto: '#E11D48', // rose-600
  inibicao: '#2563EB', // blue-600
  colisao: '#D97706', // amber-600
  conflito: '#EA580C', // orange-600
  mau_procedimento: '#CA8A04', // yellow-600
  mal_subito: '#DC2626', // red-600
  acidente: '#9333EA', // purple-600
};

export const CATEGORY_NAMES: Record<EventCategoryKey, string> = {
  furto: 'Furto',
  inibicao: 'Inibição Preventiva',
  colisao: 'Colisão',
  conflito: 'Conflito / Tumulto',
  mau_procedimento: 'Mau Procedimento',
  mal_subito: 'Mal Súbito',
  acidente: 'Acidente de Trabalho',
};

export function formatBRL(val: number): string {
  return new Intl.NumberFormat('pt-BR', {
    style: 'currency',
    currency: 'BRL',
  }).format(val);
}

export function formatDateTimeBR(isoString: string): string {
  try {
    const d = new Date(isoString);
    return `${d.toLocaleDateString('pt-BR')} às ${d.toLocaleTimeString('pt-BR', { hour: '2-digit', minute: '2-digit' })}`;
  } catch {
    return isoString;
  }
}
